# Generated by Django 2.2.7 on 2019-11-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(default='blank-book-cover.png', upload_to='book-cover/'),
        ),
    ]
