# Generated by Django 2.2.7 on 2019-11-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20191126_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reader',
        ),
        migrations.AddField(
            model_name='book',
            name='reader',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='library_app.BookHolder'),
        ),
    ]
