# Generated by Django 2.2.7 on 2019-11-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20191128_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reader',
            field=models.ManyToManyField(default=None, to='library_app.BookHolder'),
        ),
    ]
