# Generated by Django 2.2.7 on 2019-11-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_auto_20191128_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reader',
            field=models.ManyToManyField(blank=True, to='library_app.BookHolder'),
        ),
    ]
