# Generated by Django 2.2.7 on 2019-11-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_auto_20191128_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reader',
        ),
        migrations.AddField(
            model_name='book',
            name='reader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.BookHolder'),
        ),
    ]
